# Generated by Django 6.0.2 on 2026-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='medical_conditions',
        ),
        migrations.DeleteModel(
            name='MedicalCondition',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
