# Generated by Django 6.0.2 on 2026-09-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_medical_conditions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='medical_conditions',
            new_name='family_health_conditions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('not_very_active', 'Not Very Active'), ('lightly_active', 'Lightly Active'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consumes_alcohol',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('socially', 'Socially')], max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('pure_vegetarian', 'Pure Vegetarian'), ('ovo_vegetarian', 'Ovo Vegetarian'), ('non_vegetarian', 'Non Vegetarian')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exercises_regularly',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_lose', 'Weight Lose'), ('weight_gain', 'Weight Gain'), ('lifestyle_management', 'Lifestyle Management'), ('stamina_mobility', 'Stamina & Mobility'), ('strength_conditioning', 'Strength & Conditioning')], max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_report',
            field=models.FileField(blank=True, null=True, upload_to='health_reports/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('diet_training_plans', 'Diet and Training Plans'), ('personal_training', 'Personal Training'), ('both', 'Both Nutrition & Training Plans Along With An Online Trainer')], max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.CharField(blank=True, choices=[('less_than_4', 'Less than 4 hours'), ('4_5', '4-5 hours'), ('6_7', '6-7 hours'), ('8_10', '8-10 hours')], max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smokes',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('occasionally', 'Occasionally')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('cm', 'CM'), ('ft', 'FT')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
