# Generated by Django 6.0.2 on 2026-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_medical_conditions_userprofile_family_health_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calorie_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('diet_and_training', 'Diet and Training Plans'), ('personal_training_online', 'Personal Training (online, no diet plan)'), ('tailored_diet_plans', 'Diet and Tailored Plans'), ('both', 'Both Nutrition & Training Plans Along With An Online Trainer')], max_length=30),
        ),
    ]
