# Generated by Django 6.0.2 on 2026-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightlog',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
